### ISSUE TITLE
Als admin wil ik Werkgevers kunnen accepteren & weigeren bij de screening, zodat ik ze wel of niet kan aanbieden op mijn platform (M)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#10]
Acceptatiecriteria:
- [x] Overzicht van het ingediende formulier met informatie
- [x] Accepteer en weiger knop

DoD:
- [x] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [x] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [x] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [x] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [x] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [x] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [x] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by LarsVerschoor** [comment]
Bij de CompanyController.php word er bij index gecheckt of de user is ingelogd en of deze admin is, maar bij update en bij delete word dit nog niet gecheckt.

**Comment by Hidde-Scheringa** [comment]
Misschien is AdminController een betere naam, want het betreft alleen het admin gedeelde van het project.
