### ISSUE TITLE
Als gebruiker wil ik dat de werkgever mijn naam niet ziet bij mijn reactie zodat ik niet gediscrimineerd wordt. (M)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#29]
Acceptatiecriteria:
- [ ] Geen info sturen van de naam naar de werkgever

DoD:
- [ ] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [ ] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [ ] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [ ] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [ ] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [ ] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [ ] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by Hidde-Scheringa** [comment]
Planningspoker resultaat 1

**Comment by MLY-Creates** [comment]
Geschrapt omdat de de werkgever sowieso de naam van de gebruiker niet kan zien, er hoeft dus niets veranderd te worden.
