### ISSUE TITLE
Als werkgever wil ik kunnen registreren zodat, ik niet volledige afhankelijk ben van het platform bij het aanmaken van een account (M)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#3]
Acceptatiecriteria:
- [x] Registratie link voor werkgevers via de homepagina
- [x] Registratie formulier met de benodigde informatie
- [ ] Bevestigingsmail om de account te activeren
- [x] Aantonen van Gewaarmerkt KVK (betrouwbaarheid)

DoD:
- [x] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [x] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [x] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [x] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [x] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [x] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [x] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by RoshanMomand** [comment]
### Planningspoker uitkomst: 8

**Comment by Trollboy777** [comment]
auth.php meer pseudocode toevoegen voor de mensen die het niet begrijpen
