### ISSUE TITLE
Als gebruiker wil ik weten wie de werkgever is zodat ik het bedrijf kan opzoeken voordat ik reageer (M)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#30]
Acceptatiecriteria:
- [x] Werkgever duidelijk laten zien bij de vacature

DoD:
- [x] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [x] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [x] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [x] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [x] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [x] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [x] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by Hidde-Scheringa** [comment]
planningspoker resultaat 2

**Comment by MLY-Creates** [comment]
Vacatureformulier werkte niet met Company-ID meegeven, dat moet ook gefixt worden

**Comment by MLY-Creates** [comment]
Vacatureformulier gefixt, deze user story dus ook
