### ISSUE TITLE
Als werkgever wil ik dat een werkzoekende maar 1 keer kan reageren op mijn vacature zodat ik afkeuringen niet hoef te onthouden. (M)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#34]
Acceptatiecriteria:
- [x] Een systeem waardoor een werknemer's applicatie op een vacature onthouden wordt
- [ ] Al heeft de werknemer al aangemeld, blokkeer een tweede aanmelding

DoD:
- [x] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [ ] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [ ] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [ ] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [ ] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [ ] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [ ] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by Hidde-Scheringa** [comment]
planningspoker resultaten 5

**Comment by MLY-Creates** [comment]
Planningspoker: 5

**Comment by MLY-Creates** [comment]
Code werkt, maar is over het algemeen slecht leesbaar en er is duidelijk ChatGPT gebruikt zonder volledige kennis. Code kan mooiet en met zelfgemaakte notities.

**Comment by MLY-Creates** [comment]
Code is verbeterd, notities zijn duidelijker en code is logischer geschreven.
