### ISSUE TITLE
Als werkzoekende, wil ik kunnen reageren op vacatures, zodat ik mijn kansen vergroot om een passende baan te vinden.

### ISSUE THREAD

**Issue by RoshanMomand** [MLY-Creates/TLE-1-les#37]
### Acceptatiecriteria:

- [x]     Werkzoekenden kunnen een overzicht van vacatures bekijken met duidelijke filters zoals locatie, sector en type dienstverband.
- [x]     Er is een detailpagina beschikbaar voor elke vacature met uitgebreide informatie over de functie, vereisten en arbeidsvoorwaarden.
- [x]     Werkzoekenden kunnen eenvoudig reageren waardoor hun gegevens automatisch worden ingevuld maar wel anoniem blijven
- [x]     Het systeem biedt de mogelijkheid om sollicitaties te beheren, zoals een overzicht van ingediende sollicitaties en hun status.
- [x]     Werkzoekenden kunnen vacatures opslaan om er later op terug te komen.

### DoD
Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
Performance: Voldoet de applicatie aan de minimale prestatievereisten?
Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by MLY-Creates** [comment]
Code klopt en er zijn geen bugs, de filterfunctie is niet voor deze user story relevant.
