### ISSUE TITLE
Als admin wil ik werkgevers kunnen aanmaken, zodat Ik nieuwe werkgevers op het platform kan bieden (M)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#6]
Acceptatiecriteria:
- [ ] Pagina voor het aanmaken van een bedrijf
- [ ] Gegevens van het bedrijf die de aanvraag heeft gestuurd per mail met zijn of haar bedrijfsgegevens
- [ ] Gewaarmerkt kvk van het bedrijf 

DoD:
- [ ] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [ ] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [ ] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [ ] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [ ] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [ ] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [ ] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by MLY-Creates** [comment]
Scrapped: op basis van de feedback van de eerste twee sprints bleek het handiger te zijn om deze user story aan de werkgever over te laten, want uit de feedback bleek dat wij te veel taken bij de admin neerleggen, en dus meer aan de werkgever over moeten laten.
