### ISSUE TITLE
Als admin wil ik werkgeversprofielen kunnen beheren, zodat onjuiste of ongepast inhoud kan corrigeren of bedrijven op actief of inactief kan zetten (S)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#8]
Acceptatiecriteria:
- [x] Wijzigings functionaliteit voor alle werkgevers alleen voor de admin
- [x] Preview Functionaliteit wat er is gewijzigd 
- [ ] Filter functie voor laatste gewijzigd
- [ ]  Status functionaliteit om werkgevers op actief of inactief te zetten

DoD:
- [x] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [x] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [ ] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [x] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [x] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [x] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [x] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by MLY-Creates** [comment]
Filter functie was niet nodig voor deze user story, dat is namelijk een should have die beter verplaatst kan worden naar een andere user story.

Toggle status is een delete knop geworden, aangezien er binnen onze scope geen reden is om een bedrijf opnieuw aan te togglen.
