### ISSUE TITLE
Als admin wil ik Werkgevers kunnen screenen, zodat Ik kan zien of het bedrijf echt betrouwbaar is of niet (M)

### ISSUE THREAD

**Issue by ThundahPrime** [MLY-Creates/TLE-1-les#9]
Acceptatiecriteria:
- [ ] Lijst van werkgevers die geregistreerd hebben 
- [ ] Informatie en details van de werkgever die geregistreerd heeft
- [ ] Officieel gewaarmerkt KVK - Uitreksel wat klopt

DoD:
- [ ] Geen bugs: Zijn alle bekende bugs opgelost en is de code getest met voldoende testcases?
- [ ] Nette code: Is de code leesbaar, consistent en voldoet deze aan onze stijlrichtlijnen?
- [ ] Documentatie: Is er basisdocumentatie toegevoegd, zoals codecommentaar en een handleiding?
- [ ] Performance: Voldoet de applicatie aan de minimale prestatievereisten?
- [ ] Security: Zijn bekende beveiligingslekken gedicht en is er basiscontrole uitgevoerd (bijv. SQL-injectie voorkomen)?
- [ ] Toegankelijkheid: Is de basisfunctionaliteit bruikbaar met een toetsenbord en screenreader?
- [ ] Code review: Heeft minimaal één collega de code beoordeeld en goedgekeurd?

**Comment by RoshanMomand** [comment]
### Planningspoker uitkomst: 4

Inzichten : Gevoelige informatie kan belangrijk zijn is een oplet punt!

**Comment by LarsVerschoor** [comment]
Geschrapt omdat deze user-story hetzelfde is als user story 10
